services:
  db:
    image: postgres:16
    container_name: onehorizon_db
    environment:
      POSTGRES_USER: onehorizon
      POSTGRES_PASSWORD: onehorizon
      POSTGRES_DB: onehorizon
    ports:
      - "5432:5432"
    volumes:
      - onehorizon_pg:/var/lib/postgresql/data

volumes:
  onehorizon_pg:
